### ISSUE TITLE
Remove 'previous sentence' from approval modal? 

### ISSUE THREAD

**Issue by markjackson02** [markjackson02/Fable#28]
In the code it looks like we're going to show the "sentence for approval" in addition to the previously approved sentence. However I think it's better to just include the current sentence, for clarity. I think it's unnecessary to show the previous sentence as people are going to be 'caught up' with story as they are going to be reading it while the other person is working on their new sentence. 

So I propose in the approval modal, we just show the current sentence.

Agree? Please respond 'yes' or 'no', and add comments if no.

Thanks

**Comment by SeiYuri** [comment]
Agreed (yes). As you said, the display shows the story and all the latest updates directly on the screen, so all players only need to see the latest sentence to agree on it.
